query GET_POSTS {
  posts {
    unixTimeStamp
    createdAt
  }
}

query GET_POSTS($postId1: ID!, $postId2: ID!) {
  post860: post(id: $postId1){
    id
    title
    unixTimeStamp
  }
  post940: post(id: $postId2){
    id
    title
    unixTimeStamp
  }
}