query GET_POST($postId: ID!) {
  post(id: $postId) {
    ... on Post {
      id
      title
    }
  }
}

query GET_USER($userId: ID!) {
  user(id: $userId) {
    id
    firstName
    lastName
    posts {
      id
      title
    }
  }
}

query GET_POSTS {
  posts {
    id
    title
  }
}